DROP DATABASE IF EXISTS leboncoin_db;

CREATE DATABASE leboncoin_db;

USE leboncoin_db;

CREATE TABLE user (
	user_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	city VARCHAR(100) NOT NULL,
	phone_number INT
);

CREATE TABLE category (
	category_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE ad (
	ad_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price INT NOT NULL,
	creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	modification_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	user_id INT UNSIGNED NOT NULL,
	category_id INT UNSIGNED NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(user_id),
	FOREIGN KEY (category_id) REFERENCES category(category_id)
);

CREATE TABLE message (
	message_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	content VARCHAR(500) NOT NULL,
	send_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	sender_id INT UNSIGNED NOT NULL,
	receiver_id INT UNSIGNED NOT NULL,
	ad_id INT UNSIGNED,
	FOREIGN KEY (sender_id) REFERENCES user(user_id),
	FOREIGN KEY (receiver_id) REFERENCES user(user_id),
	FOREIGN KEY (ad_id) REFERENCES ad(ad_id)
);

CREATE TABLE picture (
	picture_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	url VARCHAR(255) NOT NULL,
	ad_id INT UNSIGNED NOT NULL,
	FOREIGN KEY (ad_id) REFERENCES ad(ad_id)
);
