DROP DATABASE IF EXISTS leboncoin_db;

CREATE DATABASE leboncoin_db;

USE leboncoin_db;

CREATE TABLE user (
	user_id INT AUTO_INCREMENT PRIMARY KEY,
  	name VARCHAR(100) NOT NULL,
  	email VARCHAR(255) NOT NULL UNIQUE,
  	password VARCHAR(255) NOT NULL,
  	city VARCHAR(100) NOT NULL,
  	phone VARCHAR(20),
  	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
  category_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE item (
  item_id INT AUTO_INCREMENT PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  category_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categorie(category_id)
);

CREATE TABLE message (
  message_id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  sender_id INT NOT NULL,
  receiver_id INT NOT NULL,
  item_id INT,
  FOREIGN KEY (sender_id) REFERENCES user(user_id) ON DELETE CASCADE,
  FOREIGN KEY (receiver_id) REFERENCES user(user_id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES item(item_id) ON DELETE SET NULL
);

CREATE TABLE item_image (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  item_id INT NOT NULL,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);
